### ISSUE TITLE
Install with Heimdall

### ISSUE THREAD

**Issue by be4zad** [XanderFromFortnite/TWRP_a3core#4]
Hello. Thank you for making this twrp.

Can it be booted with [Heimdall](https://github.com/Benjamin-Dobell/Heimdall)? i think an .img file is needed.

**Comment by be4zad** [comment]
i looked at the source, i think recovery.img should be installed, right?

**Comment by XanderFromFortnite** [comment]
The recovery.img is old, look in the release page

**Comment by XanderFromFortnite** [comment]
The download is a .tar file, so that it can work with odin, but if you want it to work with Heimdall, just extract the .tar file to get the .img

**Comment by XanderFromFortnite** [comment]
Now again, im still working on twrp, give me feedback

**Comment by be4zad** [comment]
Thanks. i don't have an otg cable. is it possible to reboot the phone with the power/volume keys after test?

**Comment by XanderFromFortnite** [comment]
yes, make sure you flash stock recovery back or you can't boot into the stock rom
